name: sabor_do_mar
description: Aplicativo acadêmico de uma temakeria.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto-regular.ttf
        - asset: assets/fonts/roboto-bold.ttf
          weight: 700

